### ISSUE TITLE
Create CI/CD Pipeline

### ISSUE THREAD

**Issue by madebygps** [madebygps/codespace-net-functions#2]

**Comment by madebygps** [comment]
Pipeline should deploy to Azure Functions out of process on consumption plan.

**Comment by madebygps** [comment]
I saw your PR on you branch. Looks like the Function in the portal has an error. Can you make sure FUNCTIONS_WORKER_RUNTIME is set to dotnet-isolated and not dotnet.

**Comment by rishabkumar7** [comment]
Sorry bit confused, which PR?
But yeah I might have the wrong runtime on the function app when I created it.

**Comment by rishabkumar7** [comment]
@madebygps create a PR now - #6

**Comment by madebygps** [comment]
cool! looks good, merged.
