### ISSUE TITLE
Verify codespaces access

### ISSUE THREAD

**Issue by madebygps** [madebygps/codespace-net-functions#4]
@rishabkumar7 I added you to the repo, can you let me know if you can access codesspaces from the code tab? If so, once you open it, it should be configured so that you can simply debug (f5) as soon as the setup is done. Let me know.

**Comment by rishabkumar7** [comment]
Rebuild the container, and saw this error in the output: `Error: there is no registered task type 'func'. Did you miss installing an extension that provides a corresponding task provider?`
![image](https://user-images.githubusercontent.com/45825464/198896303-7b673a39-06f2-40c4-b8a6-2bdb3187230f.png)

**Comment by rishabkumar7** [comment]
Also curious what configuration the codespaces look at to build the container?

**Comment by madebygps** [comment]
Closing since you have access!
